---
- name: Install Iptables Persistent
  apt: pkg=iptables-persistent state=installed update_cache=true
  notify:
    - Start Iptables Persistent
  when: ansible_distribution_release == 'wheezy'

- name: Install Netfilter Persistent
  apt: pkg=netfilter-persistent state=installed update_cache=true
  notify:
    - Start Netfilter Persistent
  when: ansible_distribution_release == 'jessie'
