---
- name: install
  include: install.yml
  #when: manage is not defined

- name: Set Firewall Rules
  copy: src={{ iptables_file }} dest=/etc/iptables/rules.v4 owner=root group=root mode=644
  notify:
    - Restart Iptables Persistent
    - Restart Netfilter Persistent
  #when: manage is not defined

- name: copy Firewall Rules
  copy: src={{ iptables_file }} dest=/etc/iptables/rules.v4 owner=root group=root mode=644
  notify:
    - Testing rules only
  when: manage is defined

- name: manage
  include: manage.yml
  when: manage is defined
